# **Dữ liệu định tính**
- Khái niệm: là dữ liệu phản ánh tính chất, đặc điểm, mô tả và không thể diễn tả bằng số.
- Ví dụ: Cầu thủ A chơi vị trí gì trên sân, màu xe phổ biến nhất tại VN,...

# **Dữ liệu Định lượng**
- Khái niệm: là dữ liệu dạng số, có thể đếm và đo lường được.
- Ví dụ: Cầu thủ A ghi được bao nhiêu bàn thắng, hôm nay bạn uống mấy cốc nước,..

# **Xử lý dữ liệu với Pandas**

In [1]:
import pandas as pd

# **Series**
- Khái niệm: là danh sách 1 chiều chứa dữ liệu, chỉ số phần tử (index) nằm ở danh sách khác. index có thể là bất kì kiểu dữ liệu nào trong numpy.

Ví dụ 1: index mặc định (không khai báo)
=> Series students chứa
  - Giá trị (value): ASUS, MSI, Dell, Lenovo,...
  - Chỉ số phần tử (index): 0, 1, 2,..
  - Kiểu dữ liệu của series: object (tương ứng với str)

In [2]:
brands = pd.Series(['ASUS', 'MSI', 'Dell', 'Lenovo'])
print(brands)

0      ASUS
1       MSI
2      Dell
3    Lenovo
dtype: object

Ví dụ 2: có khai báo index, index có thể không phải kiểu int

In [3]:
brands = pd.Series(['ASUS', 'MSI', 'Dell', 'Lenovo'], index=['a', 'b', 'c', 'd'])
print(brands)

a      ASUS
b       MSI
c      Dell
d    Lenovo
dtype: object

Có thể tạo Series từ dictionary (kiểu object, giống json)

In [4]:
fruits_dict = {
    'a': 'apple',
    'b': 'banana',
    'c': 'orange',
    'd': 'pear',
    'e': 'strawberry'
}
fruits = pd.Series(fruits_dict)
fruits

a         apple
b        banana
c        orange
d          pear
e    strawberry
dtype: object

### Thực hành: Thống kê cân nặng học sinh
Cho các số liệu cân nặng học sinh như sau:
|Tên|Cân nặng|
|---|--------|
|Hoa|37 kg|
|Nam|48 kg|
|Hải|42 kg|
|Linh|39kg|
|Nhân|41kg|
|Phương|38kg|
|Thu|40 kg|
|Vũ|40 kg|
|Bảo|43 kg|

Sử dụng pandas Series, tìm tên các bạn tương ứng với các cân nặng `mean`, `median`, `mode`.

In [5]:
# Chuyển data từ đề bài thành dạng Series
weight_dict = {
    'Hoa': 37,
    'Nam': 48,
    'Hải': 42,
    'Linh': 39,
    'Nhân': 41,
    'Phương': 38,
    'Thu': 40,
    'Vũ': 40,
    'Bảo': 43
}
# Tạo series
weights = pd.Series(weight_dict)
weights

Hoa       37
Nam       48
Hải       42
Linh      39
Nhân      41
Phương    38
Thu       40
Vũ        40
Bảo       43
dtype: int64

In [6]:
# Tìm tên tương ứng với mean, median, mode
    # mean (trung bình): tổng tất cả các giá trị chia cho số lượng giá trị
mean_weight = weights.mean()
    # median (trung vị): giá trị ở giữa khi series đã được sắp xếp theo giá trị
median_weight = weights.median()
    # mode: giá trị xuất hiện nhiều lần nhất
mode_weight = weights.mode()

# Hiển thị kết quả
print('Cân nặng trung bình:', mean_weight, 'kg')
print('Cân nặng trung vị:', median_weight, 'kg')
print('Cân nặng xuất hiện nhiều lần nhất:', mode_weight.values)
print('Cân nặng xuất hiện nhiều lần nhất:', end = ' ')
for i in mode_weight:
    print(i)

Cân nặng trung bình: 40.888888888888886 kg
Cân nặng trung vị: 40.0 kg
Cân nặng xuất hiện nhiều lần nhất: [40]
Cân nặng xuất hiện nhiều lần nhất: 40

**Thực hành 2: Đánh giá chất lượng dịch vụ**

In [7]:
ratings = pd.Series([4,3,1,2,1,5,4,1,1])
# Đánh giá
print(f'Chất lượng trung bình: {round(ratings.mean(),2)}/5')
print(f'Đánh giá phổ biến nhất: {ratings.mode().values[0]} sao')

Chất lượng trung bình: 2.44/5
Đánh giá phổ biến nhất: 1 sao

# **DataFrame**
- Khái niệm: là cấu trúc dữ liệu dạng 2 chiều (bảng, gồm hàng và cột)
- Mỗi cột trong DataFrame là 1 series

In [8]:
# keys: tương ứng với tên cột
# danh sách values: tương ứng với giá trị cột đó
brands = pd.DataFrame({
    'name': ['ASUS', 'MSI', 'Dell', 'Lenovo'],
    'price': [15000000, 13000000, 12000000, 10000000],
    'quantity': [10, 20, 30, 40]
})
brands

     name     price  quantity
0    ASUS  15000000        10
1     MSI  13000000        20
2    Dell  12000000        30
3  Lenovo  10000000        40

Tóm tắt thông tin DataFrame: DataFrame.info()
- RangeIndex: số bản ghi (số dòng)
- Data Colums: số cột (số Series có trong DataFrame)

In [10]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4 non-null      object
 1   price     4 non-null      int64
 2   quantity  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

DataFrame.head(n): Hiển thị n giá trị đầu của DataFrame

In [11]:
brands.head(2)

   name     price  quantity
0  ASUS  15000000        10
1   MSI  13000000        20

DataFrame.tail(n): Hiển thị n giá trị cuối của DataFrame

In [13]:
brands.tail(3)

     name     price  quantity
1     MSI  13000000        20
2    Dell  12000000        30
3  Lenovo  10000000        40

**Bài tập 1:**
Tạo một pandas DataFrame từ dữ liệu sau:
| Name | Age | Score |
| ---- | --- | ----- |
| An   | 14  | 8     |
| Bình | 15  | 7     |
| Lan  | 14  | 9     |

Yêu cầu:
- Import thư viện pandas
- Tạo DataFrame từ dữ liệu trên
- In toàn bộ bảng dữ liệu
- In riêng cột Score

In [14]:
data = {
    "Name": ["An", "Bình", "Lan"],
    "Age": [14, 15, 14],
    "Score": [8, 7, 9]
}

df = pd.DataFrame(data)

# In toàn bộ DataFrame
print('DataFrame:')
print(df)

# In cột Score
print('\nScore:')
print(df["Score"])

DataFrame:
   Name  Age  Score
0    An   14      8
1  Bình   15      7
2   Lan   14      9

Score:
0    8
1    7
2    9
Name: Score, dtype: int64

**Bài tập 2:**
| Name | Score |
| ---- | ----- |
| An   | 8     |
| Bình | 7     |
| Lan  | 9     |
| Mai  | 6     |
| Nam  | 8     |

Yêu cầu:
- Tạo DataFrame từ dữ liệu trên
- Tính: điểm trung bình (mean), điểm cao nhất (max), thấp nhất (min), điểm xuất hiện nhiều nhất (mode)
- In kết quả ra màn hình

In [15]:
data = {
    "Name": ["An", "Bình", "Lan", "Mai", "Nam"],
    "Score": [8, 7, 9, 6, 8]
}

df = pd.DataFrame(data)

mean_score = df["Score"].mean()
max_score = df["Score"].max()
min_score = df["Score"].min()
mode_score = df["Score"].mode()

print("Mean:", mean_score)
print("Max:", max_score)
print("Min:", min_score)
print("Mode:", mode_score.values[0])

Mean: 7.6
Max: 9
Min: 6
Mode: 8