In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Tải dữ liệu từ máy tính
from google.colab import files
files.upload()    # Billionaires.csv

Saving Billionaires.csv to Billionaires.csv

{'Billionaires.csv': b'"Rank","Name","Net Worth","Age","Country | Territory","Source","Industry"\r\n"1","Bernard Arnault & family","$211 B","74","France","LVMH","Fashion & Retail"\r\n"2","Elon Musk","$180 B","51","United States","Tesla, SpaceX","Automotive"\r\n"3","Jeff Bezos","$114 B","59","United States","Amazon","Technology"\r\n"4","Larry Ellison","$107 B","78","United States","Oracle","Technology"\r\n"5","Warren Buffett","$106 B","92","United States","Berkshire Hathaway","Finance & Investments"\r\n"6","Bill Gates","$104 B","67","United States","Microsoft","Technology"\r\n"7","Michael Bloomberg","$94.5 B","81","United States","Bloomberg LP","Media & Entertainment"\r\n"8","Carlos Slim Helu & family","$93 B","83","Mexico","Telecom","Telecom"\r\n"9","Mukesh Ambani","$83.4 B","65","India","Diversified","Diversified"\r\n"10","Steve Ballmer","$80.7 B","67","United States","Microsoft","Technology"\r\n"11","Francoise Bettencourt Meyers & family","$80.5 B","69","France","L\'Or\xc3\xa9al","Fashion & Retail"\r\n"12","Larry Page","$79.2 B","50","United States","Google","Technology"\r\n"13","Amancio Ortega","$77.3 B","87","Spain","Zara","Fashion & Retail"\r\n"14","Sergey Brin","$76 B","49","United States","Google","Technology"\r\n"15","Zhong Shanshan","$68 B","68","China","Beverages, pharmaceuticals","Food & Beverage"\r\n"16","Mark Zuckerberg","$64.4 B","38","United States","Facebook","Technology"\r\n"17","Charles Koch & family","$59 B","87","United States","Koch Industries","Diversified"\r\n"17","Julia Koch & family","$59 B","60","United States","Koch Industries","Diversified"\r\n"19","Jim Walton","$58.8 B","74","United States","Walmart","Fashion & Retail"\r\n"20","Rob Walton & family","$57.6 B","78","United States","Walmart","Fashion & Retail"\r\n"21","Alice Walton","$56.7 B","73","United States","Walmart","Fashion & Retail"\r\n"22","David Thomson & family","$54.4 B","65","Canada","Media","Media & Entertainment"\r\n"23","Michael Dell","$50.1 B","58","United States","Dell Technologies","Technology"\r\n"24","Gautam Adani","$47.2 B","60","India","Infrastructure, commodities","Diversified"\r\n"25","Phil Knight & family","$45.1 B","85","United States","Nike","Fashion & Retail"\r\n"26","Zhang Yiming","$45 B","39","China","TikTok","Technology"\r\n"27","Dieter Schwarz","$42.9 B","83","Germany","Retail","Fashion & Retail"\r\n"28","Fran\xc3\xa7ois Pinault & family","$40.1 B","86","France","Luxury goods","Fashion & Retail"\r\n"29","Klaus-Michael Kuehne","$39.1 B","85","Germany","Shipping","Logistics"\r\n"30","Giovanni Ferrero","$38.9 B","58","Italy","Nutella, chocolates","Food & Beverage"\r\n"31","Jacqueline Mars","$38.3 B","83","United States","Candy, pet food","Food & Beverage"\r\n"31","John Mars","$38.3 B","87","United States","Candy, pet food","Food & Beverage"\r\n"33","Li Ka-shing","$38 B","94","Hong Kong","Diversified","Diversified"\r\n"34","Ma Huateng","$35.3 B","51","China","Internet media","Technology"\r\n"35","Miriam Adelson & family","$35 B","77","United States","Casinos","Gambling & Casinos"\r\n"35","Ken Griffin","$35 B","54","United States","Hedge funds","Finance & Investments"\r\n"37","Mark Mateschitz","$34.7 B","30","Austria","Red Bull","Food & Beverage"\r\n"38","Robin Zeng","$33.4 B","54","Hong Kong","Batteries","Automotive"\r\n"39","Tadashi Yanai & family","$32.6 B","74","Japan","Fashion retail","Fashion & Retail"\r\n"40","Len Blavatnik","$32.1 B","65","United States","Music, chemicals","Diversified"\r\n"41","Alain Wertheimer","$31.6 B","74","France","Chanel","Fashion & Retail"\r\n"41","Gerard Wertheimer","$31.6 B","72","France","Chanel","Fashion & Retail"\r\n"43","Gianluigi Aponte","$31.2 B","82","Switzerland","Shipping","Logistics"\r\n"43","Rafaela Aponte-Diamant","$31.2 B","78","Switzerland","Shipping","Logistics"\r\n"45","Colin Huang","$30.2 B","43","China","E-commerce","Technology"\r\n"46","Reinhold Wuerth & family","$29.7 B","87","Germany","Fasteners","Manufacturing"\r\n"47","Lee Shau Kee","$29.5 B","95","Hong Kong","Real estate","Real Estate"\r\n"48","Jeff Yass","$28.5 B","64","United States","Trading, investments","Finance & Investments"\r\n"49","Jim Simons","$28.1 B","84","United States","Hedge funds","Finance & Investments"\r\n"50","Stephen Schwarzman","$27.8 B","76","United States","Investments","Finance & Investments"\r\n"51","Susanne Klatten","$27.4 B","60","Germany","BMW, pharmaceuticals","Automotive"\r\n"52","Gina Rinehart","$27 B","69","Australia","Mining","Metals & Mining"\r\n"53","William Ding","$26.7 B","51","China","Online games","Technology"\r\n"54","Germ\xc3\xa1n Larrea Mota Velasco & family","$26.6 B","69","Mexico","Mining","Metals & Mining"\r\n"55","Shiv Nadar","$25.6 B","77","India","software services","Technology"\r\n"56","Low Tuck Kwong","$25.5 B","74","Indonesia","Coal","Energy"\r\n"57","Thomas Peterffy","$25.3 B","78","United States","Discount brokerage","Finance & Investments"\r\n"58","Andrey Melnichenko & family","$25.2 B","51","Russia","Fertilizers, coal","Metals & Mining"\r\n"59","Stefan Quandt","$24.6 B","56","Germany","BMW","Automotive"\r\n"60","MacKenzie Scott","$24.4 B","52","United States","Amazon","Technology"\r\n"61","R. Budi Hartono","$24.2 B","82","Indonesia","Banking, tobacco","Finance & Investments"\r\n"62","Vladimir Potanin","$23.7 B","62","Russia","Metals","Metals & Mining"\r\n"63","Jack Ma","$23.5 B","58","China","E-commerce","Technology"\r\n"64","He Xiangjian & family","$23.4 B","80","China","Home appliances","Manufacturing"\r\n"65","Iris Fontbona & family","$23.1 B","80","Chile","Mining","Metals & Mining"\r\n"65","Michael Hartono","$23.1 B","83","Indonesia","Banking, tobacco","Manufacturing"\r\n"67","James Ratcliffe","$22.9 B","70","United Kingdom","Chemicals","Manufacturing"\r\n"68","Cyrus Poonawalla","$22.6 B","81","India","Vaccines","Healthcare"\r\n"69","Masayoshi Son","$22.4 B","65","Japan","Internet, telecom","Telecom"\r\n"70","Vladimir Lisin","$22.1 B","66","Russia","Steel, transport","Metals & Mining"\r\n"71","Emmanuel Besnier","$22 B","52","France","Cheese","Food & Beverage"\r\n"72","Abigail Johnson","$21.6 B","61","United States","Fidelity","Finance & Investments"\r\n"72","Leonid Mikhelson & family","$21.6 B","67","Russia","Gas, chemicals","Energy"\r\n"74","Lukas Walton","$21.2 B","36","United States","Walmart","Fashion & Retail"\r\n"74","Wang Wei","$21.2 B","52","China","Package delivery","Service"\r\n"76","Jensen Huang","$21.1 B","60","United States","Semiconductors","Technology"\r\n"77","Leonard Lauder","$21 B","90","United States","Estee Lauder","Fashion & Retail"\r\n"77","Takemitsu Takizaki","$21 B","77","Japan","Sensors","Manufacturing"\r\n"79","Alexey Mordashov & family","$20.9 B","57","Russia","Steel, investments","Metals & Mining"\r\n"80","Vagit Alekperov","$20.5 B","72","Russia","Oil","Energy"\r\n"81","Thomas Frist, Jr. & family","$20.2 B","84","United States","Hospitals","Healthcare"\r\n"82","Andrew Forrest","$19.6 B","61","Australia","Mining","Metals & Mining"\r\n"83","Ray Dalio","$19.1 B","73","United States","Hedge funds","Finance & Investments"\r\n"84","Eric Li","$19 B","59","China","Automobiles","Automotive"\r\n"84","Wang Wenyin","$19 B","55","China","Mining, copper products","Metals & Mining"\r\n"86","Eyal Ofer","$18.9 B","72","Israel","Real estate, shipping","Diversified"\r\n"86","Qin Yinglin","$18.9 B","57","China","Pig breeding","Food & Beverage"\r\n"88","Wang Chuanfu","$18.7 B","57","China","Batteries, automobiles","Automotive"\r\n"89","Harold Hamm & family","$18.5 B","77","United States","Oil & gas","Energy"\r\n"89","David Tepper","$18.5 B","65","United States","Hedge funds","Finance & Investments"\r\n"89","Gennady Timchenko","$18.5 B","70","Russia","Oil, gas","Energy"\r\n"92","Daniel Gilbert","$18 B","61","United States","Quicken Loans","Finance & Investments"\r\n"93","Lakshmi Mittal","$17.7 B","72","India","Steel","Metals & Mining"\r\n"94","Steve Cohen","$17.5 B","66","United States","Hedge funds","Finance & Investments"\r\n"94","Carl Icahn","$17.5 B","87","United States","Investments","Finance & Investments"\r\n"94","Savitri Jindal & family","$17.5 B","73","India","Steel","Metals & Mining"\r\n"97","Donald Bren","$17.4 B","90","United States","Real estate","Real Estate"\r\n"97","John Menard, Jr.","$17.4 B","83","United States","Home improvement stores","Fashion & Retail"\r\n"99","Rupert Murdoch & family","$17.1 B","92","United States","Newspapers, TV network","Media & Entertainment"\r\n"100","Vicky Safra & family","$16.7 B","70","Brazil","Banking","Finance & Investments"\r\n"101","Theo Albrecht, Jr. & family","$16.5 B","72","Germany","Aldi, Trader Joe\'s","Fashion & Retail"\r\n"101","Renata Kellnerova & family","$16.5 B","55","Czech Republic","Finance, telecommunications","Finance & Investments"\r\n"103","Li Xiting","$16.3 B","72","Singapore","medical devices","Healthcare"\r\n"104","Stefan Persson","$16.2 B","75","Sweden","H&M","Fashion & Retail"\r\n"104","Eric Schmidt","$16.2 B","67","United States","Google","Technology"\r\n"106","Michael Platt","$16 B","55","United Kingdom","Hedge funds","Finance & Investments"\r\n"107","Pang Kang","$15.9 B","67","China","Soy sauce","Food & Beverage"\r\n"108","Karl Albrecht Jr. & family","$15.8 B","N/A","Germany","Supermarkets","Fashion & Retail"\r\n"108","Beate Heister","$15.8 B","N/A","Germany","Supermarkets","Fashion & Retail"\r\n"108","Jorge Paulo Lemann & family","$15.8 B","83","Brazil","Beer","Food & Beverage"\r\n"108","Peter Woo","$15.8 B","76","Hong Kong","Real estate","Real Estate"\r\n"112","Dilip Shanghvi","$15.6 B","67","India","Pharmaceuticals","Healthcare"\r\n"113","Robert Pera","$15.5 B","45","United States","Wireless networking","Technology"\r\n"114","Radhakishan Damani","$15.3 B","68","India","Retail, investments","Fashion & Retail"\r\n"115","Huang Shilin","$15.2 B","56","China","Batteries","Automotive"\r\n"116","Dhanin Chearavanont","$14.9 B","83","Thailand","Diversified","Diversified"\r\n"116","David Green & family","$14.9 B","81","United States","Retail","Fashion & Retail"\r\n"118","Charoen Sirivadhanabhakdi","$14.8 B","78","Thailand","Alcohol, real estate","Food & Beverage"\r\n"119","Charlene de Carvalho-Heineken & family","$14.7 B","68","Netherlands","Heineken","Food & Beverage"\r\n"120","Xu Hang","$14.6 B","60","Hong Kong","Medical devices","Healthcare"\r\n"121","Wei Jianjun & family","$14.5 B","59","China","Automobiles","Automotive"\r\n"122","Alisher Usmanov","$14.4 B","69","Russia","Steel, telecom, investments","Metals & Mining"\r\n"123","Goh Cheng Liang","$14.3 B","95","Singapore","Paints","Manufacturing"\r\n"124","Kumar Birla","$14.2 B","55","India","Commodities","Diversified"\r\n"124","Aliko Dangote","$14.2 B","65","Nigeria","Cement, sugar","Manufacturing"\r\n"126","Kwong Siu-hing","$14.1 B","93","Hong Kong","Real estate","Real Estate"\r\n"127","Idan Ofer","$14 B","67","Israel","Shipping","Diversified"\r\n"128","Chen Bang","$13.9 B","57","China","Hospitals","Healthcare"\r\n"128","Lui Che Woo","$13.9 B","94","Hong Kong","Casinos/hotels","Gambling & Casinos"\r\n"130","John Fredriksen","$13.7 B","78","Cyprus","Shipping","Logistics"\r\n"130","Diane Hendricks","$13.7 B","76","United States","Building supplies","Construction & Engineering"\r\n"130","Jan Koum","$13.7 B","47","United States","WhatsApp","Technology"\r\n"133","Jerry Jones","$13.3 B","80","United States","Dallas Cowboys","Sports"\r\n"133","George Kaiser","$13.3 B","80","United States","Oil & gas, banking","Energy"\r\n"133","Joseph Lau","$13.3 B","71","Hong Kong","Real estate","Real Estate"\r\n"136","Lu Xiangyang","$13.2 B","60","China","Automobiles, batteries","Automotive"\r\n"137","Harry Triguboff","$13.1 B","90","Australia","Real estate","Real Estate"\r\n"138","Uday Kotak","$12.9 B","64","India","Banking","Finance & Investments"\r\n"138","Stanley Kroenke","$12.9 B","75","United States","Sports, real estate","Sports"\r\n"140","Mikhail Fridman","$12.6 B","58","Russia","Oil, banking, telecom","Energy"\r\n"141","Sarath Ratanavadi","$12.3 B","57","Thailand","Energy","Energy"\r\n"142","Dang Yanbao","$12.2 B","50","China","Coal","Metals & Mining"\r\n"142","Jiang Rensheng & family","$12.2 B","69","China","Vaccines","Healthcare"\r\n"144","Shahid Khan","$12.1 B","72","United States","Auto parts","Automotive"\r\n"145","Laurene Powell Jobs & family","$12 B","59","United States","Apple, Disney","Technology"\r\n"146","Robert Kuok","$11.8 B","99","Malaysia","Palm oil, shipping, property","Diversified"\r\n"147","Stephen Ross","$11.6 B","82","United States","Real estate","Real Estate"\r\n"148","Pavel Durov","$11.5 B","38","United Arab Emirates","Messaging app","Technology"\r\n"148","Andreas Struengmann & family","$11.5 B","73","Germany","Pharmaceuticals","Healthcare"\r\n"148","Thomas Struengmann & family","$11.5 B","73","Germany","Pharmaceuticals","Healthcare"\r\n"151","Liu Hanyuan","$11.4 B","59","China","Agribusiness","Food & Beverage"\r\n"151","Michael Rubin","$11.4 B","50","United States","Online retail","Fashion & Retail"\r\n"153","Israel Englander","$11.3 B","74","United States","Hedge funds","Finance & Investments"\r\n"153","Viatcheslav Kantor","$11.3 B","69","Russia","Fertilizer, real estate","Manufacturing"\r\n"153","Anthony Pratt","$11.3 B","62","Australia","Manufacturing","Manufacturing"\r\n"153","Mikhail Prokhorov","$11.3 B","57","Russia","Investments","Finance & Investments"\r\n"157","Giorgio Armani","$11.1 B","88","Italy","Luxury goods","Fashion & Retail"\r\n"157","Johann Rupert & family","$11.1 B","72","South Africa","Luxury goods","Fashion & Retail"\r\n"159","Gong Hongjia & family","$11 B","58","Hong Kong","Video surveillance","Finance & Investments"\r\n"159","Zhang Zhidong","$11 B","51","China","Internet media","Technology"\r\n"161","Philip Anschutz","$10.9 B","83","United States","Energy, sports, entertainment","Finance & Investments"\r\n"161","Judy Love & family","$10.9 B","85","United States","Gas stations","Fashion & Retail"\r\n"161","Ricardo Salinas Pliego & family","$10.9 B","67","Mexico","Retail, media","Fashion & Retail"\r\n"164","Donald Newhouse","$10.7 B","93","United States","Media","Media & Entertainment"\r\n"165","Robert Kraft","$10.6 B","81","United States","Manufacturing, New England Patriots","Sports"\r\n"165","Marcel Herrmann Telles & family","$10.6 B","73","Brazil","Beer","Food & Beverage"\r\n"167","Suleiman Kerimov & family","$10.5 B","57","Russia","Gold","Finance & Investments"\r\n"167","Sky Xu","$10.5 B","39","China","E-commerce","Fashion & Retail"\r\n"167","Changpeng Zhao","$10.5 B","45","Canada","Cryptocurrency exchange","Finance & Investments"\r\n"170","Andrew Beal","$10.3 B","70","United States","Banks, real estate","Finance & Investments"\r\n"171","Mike Cannon-Brookes","$10.2 B","43","Australia","Software","Technology"\r\n"171","Carl Cook","$10.2 B","60","United States","Medical devices","Healthcare"\r\n"171","David Duffield","$10.2 B","82","United States","Business software","Technology"\r\n"171","Jeffery Hildebrand","$10.2 B","64","United States","Oil","Energy"\r\n"171","Viktor Rashnikov","$10.2 B","74","Russia","Steel","Manufacturing"\r\n"171","Eduardo Saverin","$10.2 B","41","Brazil","Facebook","Technology"\r\n"171","Georg Schaeffler","$10.2 B","58","Germany","Auto parts","Automotive"\r\n"171","Christy Walton","$10.2 B","74","United States","Walmart","Fashion & Retail"\r\n"179","Scott Farquhar","$10.1 B","43","Australia","Software","Technology"\r\n"179","Quek Leng Chan","$10.1 B","81","Malaysia","Banking, property","Diversified"\r\n"179","Wu Yajun","$10.1 B","59","China","Real estate","Real Estate"\r\n"182","Autry Stephens","$10 B","85","United States","Oil","Energy"\r\n"183","Liu Yongxing","$9.9 B","74","China","Diversified","Service"\r\n"184","Vinod Adani","$9.8 B","74","Cyprus","Infrastructure, commodities","Diversified"\r\n"184","Nicolas Puech","$9.8 B","80","France","Hermes","Fashion & Retail"\r\n"184","Jacques Saad\xc3\xa9, Jr.","$9.8 B","51","France","Shipping","Logistics"\r\n"184","Rodolphe Saad\xc3\xa9","$9.8 B","53","France","Shipping","Logistics"\r\n"184","Tanya Saad\xc3\xa9 Zeenny","$9.8 B","55","France","Shipping","Logistics"\r\n"184","Melker Schorling & family","$9.8 B","75","Sweden","Investments","Finance & Investments"\r\n"190","Andrei Guryev & family","$9.7 B","63","Russia","Fertilizers","Manufacturing"\r\n"190","Michael Kim","$9.7 B","59","United States","Private equity","Finance & Investments"\r\n"190","Lei Jun","$9.7 B","53","China","Smartphones","Technology"\r\n"190","Friedhelm Loh","$9.7 B","76","Germany","Manufacturing","Manufacturing"\r\n"190","Sun Piaoyang","$9.7 B","64","China","Pharmaceuticals","Healthcare"\r\n"195","Rick Cohen & family","$9.6 B","70","United States","Warehouse automation","Technology"\r\n"195","Jin Baofang","$9.6 B","70","China","Solar panels","Energy"\r\n"195","Luo Liguo & family","$9.6 B","67","China","Chemicals","Manufacturing"\r\n"195","Marijke Mars","$9.6 B","58","United States","Candy, pet food","Food & Beverage"\r\n"195","Pamela Mars","$9.6 B","62","United States","Candy, pet food","Food & Beverage"\r\n"195","Valerie Mars","$9.6 B","64","United States","Candy, pet food","Food & Beverage"\r\n"195","Victoria Mars","$9.6 B","66","United States","Candy, pet food","Food & Beverage"\r\n"202","Vincent Bollor\xc3\xa9 & family","$9.5 B","71","France","Investments","Finance & Investments"\r\n"202","Jim Pattison","$9.5 B","94","Canada","Diversified","Diversified"\r\n"204","Ernesto Bertarelli","$9.4 B","57","Switzerland","Biotech, investments","Healthcare"\r\n"204","Wang Xing","$9.4 B","44","China","Food delivery","Technology"\r\n"206","Brian Chesky","$9.3 B","41","United States","Airbnb","Technology"\r\n"206","James Dyson","$9.3 B","75","United Kingdom","Vacuums","Manufacturing"\r\n"208","Roman Abramovich & family","$9.2 B","56","Russia","Steel, investments","Diversified"\r\n"208","Antonia Ax:son Johnson & family","$9.2 B","79","Sweden","Diversified","Diversified"\r\n"208","Daniel Kretinsky","$9.2 B","47","Czech Republic","Energy, investments","Energy"\r\n"208","John Malone","$9.2 B","82","United States","Cable television","Media & Entertainment"\r\n"208","Azim Premji","$9.2 B","77","India","Software services","Technology"\r\n"208","Charles Schwab","$9.2 B","85","United States","Discount brokerage","Finance & Investments"\r\n"208","Eric Smidt","$9.2 B","63","United States","Hardware stores","Fashion & Retail"\r\n"215","David Cheriton","$9 B","72","Canada","Google","Technology"\r\n"215","Ivan Glasenberg","$9 B","66","Switzerland","Mining","Metals & Mining"\r\n"215","Alexander Otto","$9 B","55","Germany","Real estate","Real Estate"\r\n"215","Anthony von Mandl","$9 B","73","Canada","Alcoholic beverages","Food & Beverage"\r\n"215","Wang Liping & family","$9 B","57","China","Hydraulic machinery","Manufacturing"\r\n"220","Finn Rausing","$8.9 B","68","Sweden","Packaging","Food & Beverage"\r\n"220","Jorn Rausing","$8.9 B","63","Sweden","Packaging","Food & Beverage"\r\n"220","Kirsten Rausing","$8.9 B","70","Sweden","Packaging","Food & Beverage"\r\n"223","Tatyana Bakalchuk","$8.8 B","47","Russia","Ecommerce","Fashion & Retail"\r\n"223","John Doerr","$8.8 B","71","United States","Venture capital","Technology"\r\n"223","Richard Liu","$8.8 B","49","China","E-commerce","Technology"\r\n"223","Dustin Moskovitz","$8.8 B","38","United States","Facebook","Technology"\r\n"223","Pierre Omidyar","$8.8 B","55","United States","EBay, PayPal","Technology"\r\n"223","Pei Zhenhua","$8.8 B","64","China","Batteries","Energy"\r\n"223","Carrie Perrodo & family","$8.8 B","72","France","Oil","Energy"\r\n"230","Chen Jianhua","$8.7 B","52","China","Chemicals","Manufacturing"\r\n"230","Michael Otto","$8.7 B","79","Germany","Retail, real estate","Fashion & Retail"\r\n"232","Leon Black","$8.6 B","71","United States","Private equity","Finance & Investments"\r\n"232","Graeme Hart","$8.6 B","67","New Zealand","Investments","Finance & Investments"\r\n"232","Ravi Jaipuria","$8.6 B","68","India","Soft drinks, fast food","Food & Beverage"\r\n"232","Hasso Plattner & family","$8.6 B","79","Ge

In [ ]:
# Đọc dữ liệu
df = pd.read_csv('Billionaires.csv', index_col = 0)
df

,Name,Net Worth,Age,Country | Territory,Source,Industry
Rank,,,,,,
1,Bernard Arnault & family,$211 B,74.0,France,LVMH,Fashion & Retail
2,Elon Musk,$180 B,51.0,United States,"Tesla, SpaceX",Automotive
3,Jeff Bezos,$114 B,59.0,United States,Amazon,Technology
4,Larry Ellison,$107 B,78.0,United States,Oracle,Technology
5,Warren Buffett,$106 B,92.0,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
2540,Yu Rong,$1 B,51.0,China,Health clinics,Healthcare
2540,"Richard Yuengling, Jr.",$1 B,80.0,United States,Beer,Food & Beverage
2540,Zhang Gongyun,$1 B,60.0,China,Tyre manufacturing machinery,Manufacturing
2540,Zhang Guiping & family,$1 B,71.0,China,Real estate,Real Estate
2540,Inigo Zobel,$1 B,66.0,Philippines,Diversified,Diversified

In [ ]:
df

,Name,Net Worth,Age,Country | Territory,Source,Industry
Rank,,,,,,
1,Bernard Arnault & family,$211 B,74.0,France,LVMH,Fashion & Retail
2,Elon Musk,$180 B,51.0,United States,"Tesla, SpaceX",Automotive
3,Jeff Bezos,$114 B,59.0,United States,Amazon,Technology
4,Larry Ellison,$107 B,78.0,United States,Oracle,Technology
5,Warren Buffett,$106 B,92.0,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...
2540,Yu Rong,$1 B,51.0,China,Health clinics,Healthcare
2540,"Richard Yuengling, Jr.",$1 B,80.0,United States,Beer,Food & Beverage
2540,Zhang Gongyun,$1 B,60.0,China,Tyre manufacturing machinery,Manufacturing
2540,Zhang Guiping & family,$1 B,71.0,China,Real estate,Real Estate
2540,Inigo Zobel,$1 B,66.0,Philippines,Diversified,Diversified

In [ ]:
# Hiển thị toàn bộ hàng và cột
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

                                          Name Net Worth    Age  \
Rank
1                     Bernard Arnault & family    $211 B   74.0
2                                    Elon Musk    $180 B   51.0
3                                   Jeff Bezos    $114 B   59.0
4                                Larry Ellison    $107 B   78.0
5                               Warren Buffett    $106 B   92.0
6                                   Bill Gates    $104 B   67.0
7                            Michael Bloomberg   $94.5 B   81.0
8                    Carlos Slim Helu & family     $93 B   83.0
9                                Mukesh Ambani   $83.4 B   65.0
10                               Steve Ballmer   $80.7 B   67.0
11       Francoise Bettencourt Meyers & family   $80.5 B   69.0
12                                  Larry Page   $79.2 B   50.0
13                              Amancio Ortega   $77.3 B   87.0
14                                 Sergey Brin     $76 B   49.0
15                              Zhong Shanshan     $68 B   68.0
16                             Mark Zuckerberg   $64.4 B   38.0
17                       Charles Koch & family     $59 B   87.0
17                         Julia Koch & family     $59 B   60.0
19                                  Jim Walton   $58.8 B   74.0
20                         Rob Walton & family   $57.6 B   78.0
21                                Alice Walton   $56.7 B   73.0
22                      David Thomson & family   $54.4 B   65.0
23                                Michael Dell   $50.1 B   58.0
24                                Gautam Adani   $47.2 B   60.0
25                        Phil Knight & family   $45.1 B   85.0
26                                Zhang Yiming     $45 B   39.0
27                              Dieter Schwarz   $42.9 B   83.0
28                   François Pinault & family   $40.1 B   86.0
29                        Klaus-Michael Kuehne   $39.1 B   85.0
30                            Giovanni Ferrero   $38.9 B   58.0
31                             Jacqueline Mars   $38.3 B   83.0
31                                   John Mars   $38.3 B   87.0
33                                 Li Ka-shing     $38 B   94.0
34                                  Ma Huateng   $35.3 B   51.0
35                     Miriam Adelson & family     $35 B   77.0
35                                 Ken Griffin     $35 B   54.0
37                             Mark Mateschitz   $34.7 B   30.0
38                                  Robin Zeng   $33.4 B   54.0
39                      Tadashi Yanai & family   $32.6 B   74.0
40                               Len Blavatnik   $32.1 B   65.0
41                            Alain Wertheimer   $31.6 B   74.0
41                           Gerard Wertheimer   $31.6 B   72.0
43                            Gianluigi Aponte   $31.2 B   82.0
43                      Rafaela Aponte-Diamant   $31.2 B   78.0
45                                 Colin Huang   $30.2 B   43.0
46                    Reinhold Wuerth & family   $29.7 B   87.0
47                                Lee Shau Kee   $29.5 B   95.0
48                                   Jeff Yass   $28.5 B   64.0
49                                  Jim Simons   $28.1 B   84.0
50                          Stephen Schwarzman   $27.8 B   76.0
51                             Susanne Klatten   $27.4 B   60.0
52                               Gina Rinehart     $27 B   69.0
53                                William Ding   $26.7 B   51.0
54         Germán Larrea Mota Velasco & family   $26.6 B   69.0
55                                  Shiv Nadar   $25.6 B   77.0
56                              Low Tuck Kwong   $25.5 B   74.0
57                             Thomas Peterffy   $25.3 B   78.0
58                 Andrey Melnichenko & family   $25.2 B   51.0
59                               Stefan Quandt   $24.6 B   56.0
60                             MacKenzie Scott   $24.4 B   52.0
61                             R. Budi Hartono   $24.2 B   82.0
62                            Vladimir Potanin   $23.7 B   62.0
63                                     Jack Ma   $23.5 B   58.0
64                       He Xiangjian & family   $23.4 B   80.0
65                      Iris Fontbona & family   $23.1 B   80.0
65                             Michael Hartono   $23.1 B   83.0
67                             James Ratcliffe   $22.9 B   70.0
68                            Cyrus Poonawalla   $22.6 B   81.0
69                               Masayoshi Son   $22.4 B   65.0
70                              Vladimir Lisin   $22.1 B   66.0
71                            Emmanuel Besnier     $22 B   52.0
72                             Abigail Johnson   $21.6 B   61.0
72                   Leonid Mikhelson & family   $21.6 B   67.0
74                                Lukas Walton   $21.2 B   36.0
74                                    Wang Wei   $21.2 B   52.0
76                                Jensen Huang   $21.1 B   60.0
77                              Leonard Lauder     $21 B   90.0
77                          Takemitsu Takizaki     $21 B   77.0
79                   Alexey Mordashov & family   $20.9 B   57.0
80                             Vagit Alekperov   $20.5 B   72.0
81                  Thomas Frist, Jr. & family   $20.2 B   84.0
82                              Andrew Forrest   $19.6 B   61.0
83                                   Ray Dalio   $19.1 B   73.0
84                                     Eric Li     $19 B   59.0
84                                 Wang Wenyin     $19 B   55.0
86                                   Eyal Ofer   $18.9 B   72.0
86                                 Qin Yinglin   $18.9 B   57.0
88                                Wang Chuanfu   $18.7 B   57.0
89                        Harold Hamm & family   $18.5 B   77.0
89                                David Tepper   $18.5 B   65.0
89                           Gennady Timchenko   $18.5 B   70.0
92                              Daniel Gilbert     $18 B   61.0
93                              Lakshmi Mittal   $17.7 B   72.0
94                                 Steve Cohen   $17.5 B   66.0
94                                  Carl Icahn   $17.5 B   87.0
94                     Savitri Jindal & family   $17.5 B   73.0
97                                 Donald Bren   $17.4 B   90.0
97                            John Menard, Jr.   $17.4 B   83.0
99                     Rupert Murdoch & family   $17.1 B   92.0
100                       Vicky Safra & family   $16.7 B   70.0
101                Theo Albrecht, Jr. & family   $16.5 B   72.0
101                 Renata Kellnerova & family   $16.5 B   55.0
103                                  Li Xiting   $16.3 B   72.0
104                             Stefan Persson   $16.2 B   75.0
104                               Eric Schmidt   $16.2 B   67.0
106                              Michael Platt     $16 B   55.0
107                                  Pang Kang   $15.9 B   67.0
108                 Karl Albrecht Jr. & family   $15.8 B    NaN
108                              Beate Heister   $15.8 B    NaN
108                Jorge Paulo Lemann & family   $15.8 B   83.0
108                                  Peter Woo   $15.8 B   76.0
112                             Dilip Shanghvi   $15.6 B   67.0
113                                Robert Pera   $15.5 B   45.0
114                         Radhakishan Damani   $15.3 B   68.0
115                               Huang Shilin   $15.2 B   56.0
116                        Dhanin Chearavanont   $14.9 B   83.0
116                       David Green & family   $14.9 B   81.0
118                  Charoen Sirivadhanabhakdi   $14.8 B   78.0
119     Charlene de Carvalho-Heineken & family   $14.7 B   68.0
120                                    Xu Hang   $14.6 B   60.0
121                       Wei Jianjun & family   $14.5 B   59.0
122                            Alisher Usmanov   $14.4 B   69.0
123                            Goh Cheng Liang   $14.3 B   95.0
124                                Kumar Birla   $14.2 B   55.0
124                              Aliko Dangote   $14.2 B   65.0
126                             Kwong Siu-hing   $14.1 B   93.0
127                                  Idan Ofer     $14 B   67.0
128                                  Chen Bang   $13.9 B   57.0
128                                Lui Che Woo   $13.9 B   94.0
130                            John Fredriksen   $13.7 B   78.0
130                            Diane Hendricks   $13.7 B   76.0
130                                   Jan Koum   $13.7 B   47.0
133                                Jerry Jones   $13.3 B   80.0
133                              George Kaiser   $13.3 B   80.0
133                                 Joseph Lau   $13.3 B   71.0
136                               Lu Xiangyang   $13.2 B   60.0
137                            Harry Triguboff   $13.1 B   90.0
138                                 Uday Kotak   $12.9 B   64.0
138                            Stanley Kroenke   $12.9 B   75.0
140                            Mikhail Fridman   $12.6 B   58.0
141                          Sarath Ratanavadi   $12.3 B   57.0
142                                Dang Yanbao   $12.2 B   50.0
142                    Jiang Rensheng & family   $12.2 B   69.0
144                                Shahid Khan   $12.1 B   72.0
145               Laurene Powell Jobs & family     $12 B   59.0
146                                Robert Kuok   $11.8 B   99.0
147                               Stephen Ross   $11.6 B   82.0
148                                Pavel Durov   $11.5 B   38.0
148               Andreas Struengmann & family   $11.5 B   73.0
148                Thomas Struengmann & family   $11.5 B   73.0
151                                Liu Hanyuan   $11.4 B   59.0
151                              Michael Rubin   $11.4 B   50.0
153                           Israel Englander   $11.3 B   74.0
153                         Viatcheslav Kantor   $11.3 B   69.0
153                              Anthony Pratt   $11.3 B   62.0
153                          Mikhail Prokhorov   $11.3 B   57.0
157                             Giorgio Armani   $11.1 B   88.0
157                     Johann Rupert & family   $11.1 B   72.0
159                      Gong Hongjia & family     $11 B   58.0
159                              Zhang Zhidong     $11 B   51.0
161                            Philip Anschutz   $10.9 B   83.0
161                         Judy Love & family   $10.9 B   85.0
161            Ricardo Salinas Pliego & family   $10.9 B   67.0
164                            Donald Newhouse   $10.7 B   93.0
165                               Robert Kraft   $10.6 B   81.0
165            Marcel Herrmann Telles & family   $10.6 B   73.0
167                  Suleiman Kerimov & family   $10.5 B   57.0
167                                     Sky Xu   $10.5 B   39.0
167                             Changpeng Zhao   $10.5 B   45.0
170                                Andrew Beal   $10.3 B   70.0
171                        Mike Cannon-Brookes   $10.2 B   43.0
171                                  Carl Cook   $10.2 B   60.0
171                             David Duffield   $10.2 B   82.0
171                         Jeffery Hildebrand   $10.2 B   64.0
171                           Viktor Rashnikov   $10.2 B   74.0
171                            Eduardo Saverin   $10.2 B   41.0
171                           Georg Schaeffler   $10.2 B   58.0
171                             Christy Walton   $10.2 B   74.0
179                             Scott Farquhar   $10.1 B   43.0
179                             Quek Leng Chan   $10.1 B   81.0
179                                   Wu Yajun   $10.1 B   59.0
182                             Autry Stephens     $10 B   85.0
183                               Liu Yongxing    $9.9 B   74.0
184                                Vinod Adani    $9.8 B   74.0
184                              Nicolas Puech    $9.8 B   80.0
184                         Jacques Saadé, Jr.    $9.8 B   51.0
184                             Rodolphe Saadé    $9.8 B   53.0
184                         Tanya Saadé Zeenny    $9.8 B   55.0
184                  Melker Schorling & family    $9.8 B   75.0
190                     Andrei Guryev & family    $9.7 B   63.0
190                                Michael Kim    $9.7 B   59.0
190                                    Lei Jun    $9.7 B   53.0
190                              Friedhelm Loh    $9.7 B   76.0
190                               Sun Piaoyang    $9.7 B   64.0
195                        Rick Cohen & family    $9.6 B   70.0
195                                Jin Baofang    $9.6 B   70.0
195                         Luo Liguo & family    $9.6 B   67.0
195                               Marijke Mars    $9.6 B   58.0
195                                Pamela Mars    $9.6 B   62.0
195                               Valerie Mars    $9.6 B   64.0
195                              Victoria Mars    $9.6 B   66.0
202                   Vincent Bolloré & family    $9.5 B   71.0
202                               Jim Pattison    $9.5 B   94.0
204                         Ernesto Bertarelli    $9.4 B   57.0
204                                  Wang Xing    $9.4 B   44.0
206                               Brian Chesky    $9.3 B   41.0
206                                James Dyson    $9.3 B   75.0
208                  Roman Abramovich & family    $9.2 B   56.0
208            Antonia Ax:son Johnson & family    $9.2 B   79.0
208                           Daniel Kretinsky    $9.2 B   47.0
208                                John Malone    $9.2 B   82.0
208                                Azim Premji    $9.2 B   77.0
208                             Charles Schwab    $9.2 B   85.0
208                                 Eric Smidt    $9.2 B   63.0
215                             David Cheriton      $9 B   72.0
215                            Ivan Glasenberg      $9 B   66.0
215                             Alexander Otto      $9 B   55.0
215                          Anthony von Mandl      $9 B   73.0
215                       Wang Liping & family      $9 B   57.0
220                               Finn Rausing    $8.9 B   68.0
220                               Jorn Rausing    $8.9 B   63.0
220                            Kirsten Rausing    $8.9 B   70.0
223                          Tatyana Bakalchuk    $8.8 B   47.0
223                                 John Doerr    $8.8 B   71.0
223                                Richard Liu    $8.8 B   49.0
223                           Dustin Moskovitz    $8.8 B   38.0
223                             Pierre Omidyar    $8.8 B   55.0
223                                Pei Zhenhua    $8.8 B   64.0
223                    Carrie Perrodo & family    $8.8 B   72.0
230                               Chen Jianhua    $8.7 B   52.0
230                               Michael Otto    $8.7 B   79.0
232                                 Leon Black    $8.6 B   71.0
232                                Graeme Hart    $8.6 B   67.0
232                              Ravi Jaipuria    $8.6 B   68.0
232                    Hasso Plattner & family    $8.6 B   79.0
232           Carlos Alberto Sicupira & family    $8.6 B   75.0
232                              Manuel Villar    $8.6 B   73.0
232          Andreas von Bechtolsheim & family    $8.6 B   67.0
239                        Chase Coleman, III.    $8.5 B   47.0
239                         Ann Walton Kroenke    $8.5 B   74.0
239                        Li Zhenguo & family    $8.5 B   55.0
242                                Jim Kennedy    $8.4 B   75.0
242                 Nicky Oppenheimer & family    $8.4 B   77.0
242                         Blair Parry-Okeden    $8.4 B   72.0
242                    Zheng Shuliang & family    $8.4 B   77.0
246                                John Morris    $8.3 B   75.0
246                            Stefano Pessina    $8.3 B   81.0
246                Francine von Finck & family    $8.3 B    NaN
249                               Francis Choi    $8.2 B   75.0
249                                German Khan    $8.2 B   61.0
249                           Abdulsamad Rabiu    $8.2 B   62.0
249                             George Roberts    $8.2 B   79.0
249                           Kushal Pal Singh    $8.2 B   91.0
249                               Wang Jianlin    $8.2 B   68.0
249                       Yang Huiyan & family    $8.2 B   41.0
256                           Laurent Dassault    $8.1 B   69.0
256                           Thierry Dassault    $8.1 B   66.0
256                            Tilman Fertitta    $8.1 B   65.0
256               Marie-Hélène Habert-Dassault    $8.1 B   58.0
256                              Karel Komarek    $8.1 B   54.0
261                         Nathan Blecharczyk      $8 B   39.0
261                               Leonid Fedun      $8 B   66.0
261                             Bernard Marcus      $8 B   93.0
261                               Patrick Ryan      $8 B   85.0
261                            Robert F. Smith      $8 B   60.0
261                                Pavel Tykac      $8 B   58.0
261                              Eric Wittouck      $8 B   76.0
268                              Orlando Bravo    $7.9 B   52.0
268                              Ding Shizhong    $7.9 B   52.0
268                        Nancy Walton Laurie    $7.9 B   71.0
268                                 Jay Y. Lee    $7.9 B   54.0
268                             Ramzi Musallam    $7.9 B   54.0
268                                 David Shaw    $7.9 B   72.0
268                      Andrei Skoch & family    $7.9 B   57.0
268                               Georg Stumpf    $7.9 B   50.0
276                             Rocco Commisso    $7.8 B   73.0
276                       Li Shuirong & family    $7.8 B   66.0
276                               Lin Shu-hong    $7.8 B   94.0
276                            Qi Shi & family    $7.8 B   53.0
276                              Yao Liangsong    $7.8 B   58.0
276                             Zhang Congyuan    $7.8 B   75.0
282                        Jean-Michel Besnier    $7.7 B   55.0
282                    Marie Besnier Beauvalot    $7.7 B   42.0
282                               David Geffen    $7.7 B   80.0
282                                   Robin Li    $7.7 B   54.0
282                       Liu Yonghao & family    $7.7 B   71.0
282                              Henry Samueli    $7.7 B   68.0
282                        Reinhold Schmieding    $7.7 B   68.0
282                             Ivar Tollefsen    $7.7 B   61.0
290                                Cao Renxian    $7.6 B   54.0
290                   Hasmukh Chudgar & family    $7.6 B   89.0
290                              Andrew Currie    $7.6 B   67.0
290                                 Joe Gebbia    $7.6 B   41.0
290                                  Philip Ng    $7.6 B   64.0
290                                 John Reece    $7.6 B   66.0
290                              Leonard Stern    $7.6 B   85.0
290                                Joseph Tsai    $7.6 B   59.0
290                              Zhong Huijuan    $7.6 B   62.0
299                               Arthur Blank    $7.5 B   80.0
299                               Charles Butt    $7.5 B   85.0
299                                Ding Shijia    $7.5 B   59.0
299                      Paul Tudor Jones, II.    $7.5 B   68.0
299                               Henry Kravis    $7.5 B   79.0
299                                 Zhang Yong    $7.5 B   52.0
305                            James Goodnight    $7.4 B   80.0
305                          Sri Prakash Lohia    $7.4 B   70.0
305                                Ma Jianrong    $7.4 B   59.0
305                                  Robert Ng    $7.4 B   71.0
305                               Steven Rales    $7.4 B   72.0
305                             Nassef Sawiris    $7.4 B   62.0
305                                Harry Stine    $7.4 B   81.0

In [ ]:
# Check nhanh thông tin data
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2640 entries, 1 to 2540
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2640 non-null   object
 1   Net Worth            2640 non-null   object
 2   Age                  2576 non-null   float64
 3   Country | Territory  2640 non-null   object
 4   Source               2640 non-null   object
 5   Industry             2640 non-null   object
dtypes: float64(1), object(5)
memory usage: 144.4+ KB

## **Biến đổi dữ liệu**

**Hàm biến đổi dữ liệu cột Net Worth**

In [ ]:
def clean_networth(networth):
  # Xóa ký tự đầu và cuối: '$211 B' => '211 '
  return networth[1:-1].strip()

**DataFrame.apply(): thay đổi giá trị 1 cột bằng hàm tự định nghĩa**

In [ ]:
df["Net Worth"] = df["Net Worth"].apply(clean_networth)

**Chuyển đổi kiểu dữ liệu của cột**

In [ ]:
# pd.to_numeric(<cột>): chuyển string => float
df["Net Worth"] = pd.to_numeric(df["Net Worth"])

In [ ]:
# Biến đổi dữ liệu cột age: float -> int
df["Age"] = df["Age"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2640 entries, 1 to 2540
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2640 non-null   object
 1   Net Worth            2640 non-null   float64
 2   Age                  2576 non-null   float64
 3   Country | Territory  2640 non-null   object
 4   Source               2640 non-null   object
 5   Industry             2640 non-null   object
dtypes: float64(2), object(4)
memory usage: 144.4+ KB

## **Nhóm và Sắp xếp**

Đề bài: "Đưa ra tổng tài sản lớn nhất của các tỉ phú nằm ở lĩnh vực nào"
<br>
=> Cần tính tổng lượng tài sản theo từng lĩnh vực

In [ ]:
# Tính tổng tài sản (Net Worth) theo lĩnh vực (Industry)
df_industry = df[['Industry', 'Net Worth']].groupby('Industry').sum()
df_industry

                            Net Worth
Industry
Automotive                      525.3
Construction & Engineering      118.5
Diversified                     905.2
Energy                          453.5
Fashion & Retail               1698.8
Finance & Investments          1605.1
Food & Beverage                 957.2
Gambling & Casinos              120.5
Healthcare                      643.2
Logistics                       239.5
Manufacturing                  1025.9
Media & Entertainment           427.5
Metals & Mining                 446.8
Real Estate                     657.4
Service                         173.4
Sports                          134.5
Technology                     1871.0
Telecom                         203.5

In [ ]:
# sắp xếp tăng dần
df_industry = df_industry.sort_values(by='Net Worth', ascending=False)
df_industry

                            Net Worth
Industry
Technology                     1871.0
Fashion & Retail               1698.8
Finance & Investments          1605.1
Manufacturing                  1025.9
Food & Beverage                 957.2
Diversified                     905.2
Real Estate                     657.4
Healthcare                      643.2
Automotive                      525.3
Energy                          453.5
Metals & Mining                 446.8
Media & Entertainment           427.5
Logistics                       239.5
Telecom                         203.5
Service                         173.4
Sports                          134.5
Gambling & Casinos              120.5
Construction & Engineering      118.5

Ví dụ 1: Tính tổng tài sản theo quốc gia
<br>
=> Top 5 quốc gia giàu nhất

In [ ]:
df_country = df[['Country | Territory', 'Net Worth']].groupby('Country | Territory').sum()
df_country = df_country.sort_values(by='Net Worth', ascending=False)
df_country.head(5)

                     Net Worth
Country | Territory
United States           4489.0
China                   1644.7
India                    674.8
France                   590.0
Germany                  585.4

Ví dụ 2: Số lượng tỷ phú mỗi quốc gia
<br>
=> Quốc gia có nhiều tỷ phú nhất

In [ ]:
amount_billionaires = df[['Country | Territory', 'Name']].groupby('Country | Territory').count()
amount_billionaires = amount_billionaires.sort_values(by='Name', ascending=False)
amount_billionaires.head(1)

                     Name
Country | Territory
United States         734

## **Làm sạch dữ liệu**

In [ ]:
from google.colab import files
files.upload()    # hockey_players_data.csv

Saving hockey_players_data.csv to hockey_players_data.csv

{'hockey_players_data.csv': b'number,name,position,games_played,goals,assists,PIM,birthdate,age,birthplace,weight,height\n13,Mikyla Grant-Mentis,F,6,5.0,4,4,7/15/98,22,"Brampton, ONT",,5.08\n44,Lindsay Eastwood,D,6,4.0,5,10,1/14/97,23,,,5.08\n2,Taylor Woods,F,6,4.0,4,4,4/12/94,26,"Thunder Bay,ONT",160.0,5.04\n19,Brooke Boquist,F,6,2.0,2,2,7/27/96,24,"Burford,ONT",,5.03\n67,Emma Woods,F,6,,4,0,9/8/96,24,"Markham,ONT",155.0,5.04\n21,Breanne Wilson-Bennett,F,6,2.0,4,2,3/5/96,24,"Goose Bay, Newfoundland",,5.03\n27,Amy Curlew,F,6,,2,4,3/4/97,23,"Rouyn-Noranda, PQ",,5.07\n27,Sarah-Eve Coutu-Godbout,F,6,2.0,4,2,6/16/97,23,,,\n18,Taytum Clairmont,F,6,1.0,3,21,11/28/93,26,"Royal Oak, MI",177.0,5.11\n18,Taytum Clairmont,F,6,1.0,3,21,11/28/93,26,"Royal Oak, MI",177.0,5.11\n27,Shiann Darkangelo,F,6,,3,0,1/4/97,22,"Richmond Hill, ONT",,5.08\n7,Mackenzie MacNeil,F,6,2.0,1,1,9/3/96,24,"Bourne, MA",,5.08\n12,Emily Fluke,F,6,1.0,4,4,5/8/94,27,"Stratford, PEI",,5.07\n4,Sarah Steele,D,6,1.0,4,4,9/11/94,25,"Belleville, ONT",145.0,5.06\n23,Megan Quinn,D,6,1.0,0,0,3/9/95,22,"Burlington, ONT",165.0,5.05\n25,Emma Greco,D,6,,0,0,4/27/97,22,"Thornhill, ONT",150.0,5.08\n15,Natalie Marcuzzi,F,6,,0,0,10/30/97,27,"Schreiber, ONT",135.0,5.08\n91,Jenna McParland,F,6,,0,0,5/2/87,33,"Hamilton, ONT",140.0,5.08\n91,Henna McParland,M,5,,0,0,3/2/87,33,"Hamilton, ONT",140.0,5.08\n27,Kristen Barbara,D,6,,0,0,5/16/94,26,"Brampton, ONT",,5.1\n29,Julie Allen,F,6,,0,0,5/16/94,26,"Waterford, ONT",145.0,5.07\n34,Elaine Chuli,G,6,,0,0,7/16/96,24,"Outlook, SASK",,5.11\n'}

In [ ]:
df = pd.read_csv('hockey_players_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   number        22 non-null     int64
 1   name          22 non-null     object
 2   position      22 non-null     object
 3   games_played  22 non-null     int64
 4   goals         12 non-null     float64
 5   assists       22 non-null     int64
 6   PIM           22 non-null     int64
 7   birthdate     22 non-null     object
 8   age           22 non-null     int64
 9   birthplace    20 non-null     object
 10  weight        11 non-null     float64
 11  height        21 non-null     float64
dtypes: float64(3), int64(5), object(4)
memory usage: 2.2+ KB

In [ ]:
df

,number,name,position,games_played,goals,assists,PIM,birthdate,age,birthplace,weight,height
0,13,Mikyla Grant-Mentis,F,6,5.0,4,4,7/15/98,22,"Brampton, ONT",NaN,5.08
1,44,Lindsay Eastwood,D,6,4.0,5,10,1/14/97,23,NaN,NaN,5.08
2,2,Taylor Woods,F,6,4.0,4,4,4/12/94,26,"Thunder Bay,ONT",160.0,5.04
3,19,Brooke Boquist,F,6,2.0,2,2,7/27/96,24,"Burford,ONT",NaN,5.03
4,67,Emma Woods,F,6,NaN,4,0,9/8/96,24,"Markham,ONT",155.0,5.04
5,21,Breanne Wilson-Bennett,F,6,2.0,4,2,3/5/96,24,"Goose Bay, Newfoundland",NaN,5.03
6,27,Amy Curlew,F,6,NaN,2,4,3/4/97,23,"Rouyn-Noranda, PQ",NaN,5.07
7,27,Sarah-Eve Coutu-Godbout,F,6,2.0,4,2,6/16/97,23,NaN,NaN,NaN
8,18,Taytum Clairmont,F,6,1.0,3,21,11/28/93,26,"Royal Oak, MI",177.0,5.11
9,18,Taytum Clairmont,F,6,1.0,3,21,11/28/93,26,"Royal Oak, MI",177.0,5.11
10,27,Shiann Darkangelo,F,6,NaN,3,0,1/4/97,22,"Richmond Hill, ONT",NaN,5.08
11,7,Mackenzie MacNeil,F,6,2.0,1,1,9/3/96,24,"Bourne, MA",NaN,5.08
12,12,Emily Fluke,F,6,1.0,4,4,5/8/94,27,"Stratford, PEI",NaN,5.07
13,4,Sarah Steele,D,6,1.0,4,4,9/11/94,25,"Belleville, ONT",145.0,5.06
14,23,Megan Quinn,D,6,1.0,0,0,3/9/95,22,"Burlington, ONT",165.0,5.05
15,25,Emma Greco,D,6,NaN,0,0,4/27/97,22,"Thornhill, ONT",150.0,5.08
16,15,Natalie Marcuzzi,F,6,NaN,0,0,10/30/97,27,"Schreiber, ONT",135.0,5.08
17,91,Jenna McParland,F,6,NaN,0,0,5/2/87,33,"Hamilton, ONT",140.0,5.08
18,91,Henna McParland,M,5,NaN,0,0,3/2/87,33,"Hamilton, ONT",140.0,5.08
19,27,Kristen Barbara,D,6,NaN,0,0,5/16/94,26,"Brampton, ONT",NaN,5.10
20,29,Julie Allen,F,6,NaN,0,0,5/16/94,26,"Waterford, ONT",145.0,5.07
21,34,Elaine Chuli,G,6,NaN,0,0,7/16/96,24,"Outlook, SASK",NaN,5.11

In [ ]:
# Đếm các giá trị bị thiếu
df.isnull().sum()

number           0
name             0
position         0
games_played     0
goals           10
assists          0
PIM              0
birthdate        0
age              0
birthplace       2
weight          11
height           1
dtype: int64

dropna(): bỏ tất cả các hàng có giá trị bị khuyết: df.dropna()
<br>
Nếu muốn bỏ cột, thì kết hợp với axis=1: df.dropna(axis=1)

In [ ]:
# Loại bỏ 1 số cột không cần thiết: 'birthdate', 'birthplace'
df.drop(['birthdate', 'birthplace'], axis=1, inplace=True)
df

,number,name,position,games_played,goals,assists,PIM,age,weight,height
0,13,Mikyla Grant-Mentis,F,6,5.0,4,4,22,NaN,5.08
1,44,Lindsay Eastwood,D,6,4.0,5,10,23,NaN,5.08
2,2,Taylor Woods,F,6,4.0,4,4,26,160.0,5.04
3,19,Brooke Boquist,F,6,2.0,2,2,24,NaN,5.03
4,67,Emma Woods,F,6,NaN,4,0,24,155.0,5.04
5,21,Breanne Wilson-Bennett,F,6,2.0,4,2,24,NaN,5.03
6,27,Amy Curlew,F,6,NaN,2,4,23,NaN,5.07
7,27,Sarah-Eve Coutu-Godbout,F,6,2.0,4,2,23,NaN,NaN
8,18,Taytum Clairmont,F,6,1.0,3,21,26,177.0,5.11
9,18,Taytum Clairmont,F,6,1.0,3,21,26,177.0,5.11
10,27,Shiann Darkangelo,F,6,NaN,3,0,22,NaN,5.08
11,7,Mackenzie MacNeil,F,6,2.0,1,1,24,NaN,5.08
12,12,Emily Fluke,F,6,1.0,4,4,27,NaN,5.07
13,4,Sarah Steele,D,6,1.0,4,4,25,145.0,5.06
14,23,Megan Quinn,D,6,1.0,0,0,22,165.0,5.05
15,25,Emma Greco,D,6,NaN,0,0,22,150.0,5.08
16,15,Natalie Marcuzzi,F,6,NaN,0,0,27,135.0,5.08
17,91,Jenna McParland,F,6,NaN,0,0,33,140.0,5.08
18,91,Henna McParland,M,5,NaN,0,0,33,140.0,5.08
19,27,Kristen Barbara,D,6,NaN,0,0,26,NaN,5.10
20,29,Julie Allen,F,6,NaN,0,0,26,145.0,5.07
21,34,Elaine Chuli,G,6,NaN,0,0,24,NaN,5.11

fillna(): thay thế các giá trị NaN thành giá trị mặc định

In [ ]:
# Thay thế giá trị NaN thành 0 trong cột goals
df.goals = df.goals.fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   number        22 non-null     int64
 1   name          22 non-null     object
 2   position      22 non-null     object
 3   games_played  22 non-null     int64
 4   goals         22 non-null     float64
 5   assists       22 non-null     int64
 6   PIM           22 non-null     int64
 7   age           22 non-null     int64
 8   weight        11 non-null     float64
 9   height        21 non-null     float64
dtypes: float64(3), int64(5), object(2)
memory usage: 1.8+ KB

Kiểm tra dữ liệu lặp

In [ ]:
# Đếm số dòng trùng nhau
df.duplicated().sum()

np.int64(1)

In [ ]:
# Xóa các dòng trùng nhau
df.drop_duplicates()

,number,name,position,games_played,goals,assists,PIM,age,weight,height
0,13,Mikyla Grant-Mentis,F,6,5.0,4,4,22,NaN,5.08
1,44,Lindsay Eastwood,D,6,4.0,5,10,23,NaN,5.08
2,2,Taylor Woods,F,6,4.0,4,4,26,160.0,5.04
3,19,Brooke Boquist,F,6,2.0,2,2,24,NaN,5.03
4,67,Emma Woods,F,6,0.0,4,0,24,155.0,5.04
5,21,Breanne Wilson-Bennett,F,6,2.0,4,2,24,NaN,5.03
6,27,Amy Curlew,F,6,0.0,2,4,23,NaN,5.07
7,27,Sarah-Eve Coutu-Godbout,F,6,2.0,4,2,23,NaN,NaN
8,18,Taytum Clairmont,F,6,1.0,3,21,26,177.0,5.11
10,27,Shiann Darkangelo,F,6,0.0,3,0,22,NaN,5.08
11,7,Mackenzie MacNeil,F,6,2.0,1,1,24,NaN,5.08
12,12,Emily Fluke,F,6,1.0,4,4,27,NaN,5.07
13,4,Sarah Steele,D,6,1.0,4,4,25,145.0,5.06
14,23,Megan Quinn,D,6,1.0,0,0,22,165.0,5.05
15,25,Emma Greco,D,6,0.0,0,0,22,150.0,5.08
16,15,Natalie Marcuzzi,F,6,0.0,0,0,27,135.0,5.08
17,91,Jenna McParland,F,6,0.0,0,0,33,140.0,5.08
18,91,Henna McParland,M,5,0.0,0,0,33,140.0,5.08
19,27,Kristen Barbara,D,6,0.0,0,0,26,NaN,5.10
20,29,Julie Allen,F,6,0.0,0,0,26,145.0,5.07
21,34,Elaine Chuli,G,6,0.0,0,0,24,NaN,5.11

Xử lý kiểu dữ liệu

In [ ]:
# Chuyển age: float => int
df.age = df.age.astype("int")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   number        22 non-null     int64
 1   name          22 non-null     object
 2   position      22 non-null     object
 3   games_played  22 non-null     int64
 4   goals         22 non-null     float64
 5   assists       22 non-null     int64
 6   PIM           22 non-null     int64
 7   age           22 non-null     int64
 8   weight        11 non-null     float64
 9   height        21 non-null     float64
dtypes: float64(3), int64(5), object(2)
memory usage: 1.8+ KB

Kiểm tra dữ liệu có điều kiện

In [ ]:
# Loại bỏ chiều cao, cân nặng âm
df = df[df["weight"] > 0]
df = df[df["height"] > 0]
df

,number,name,position,games_played,goals,assists,PIM,age,weight,height
2,2,Taylor Woods,F,6,4.0,4,4,26,160.0,5.04
4,67,Emma Woods,F,6,0.0,4,0,24,155.0,5.04
8,18,Taytum Clairmont,F,6,1.0,3,21,26,177.0,5.11
9,18,Taytum Clairmont,F,6,1.0,3,21,26,177.0,5.11
13,4,Sarah Steele,D,6,1.0,4,4,25,145.0,5.06
14,23,Megan Quinn,D,6,1.0,0,0,22,165.0,5.05
15,25,Emma Greco,D,6,0.0,0,0,22,150.0,5.08
16,15,Natalie Marcuzzi,F,6,0.0,0,0,27,135.0,5.08
17,91,Jenna McParland,F,6,0.0,0,0,33,140.0,5.08
18,91,Henna McParland,M,5,0.0,0,0,33,140.0,5.08
20,29,Julie Allen,F,6,0.0,0,0,26,145.0,5.07

Chuẩn hóa dữ liệu dạng text

In [ ]:
# Viết thường tất cả tên
df['name'] = df['name'].str.lower().str.strip()
df

,number,name,position,games_played,goals,assists,PIM,age,weight,height
2,2,taylor woods,F,6,4.0,4,4,26,160.0,5.04
4,67,emma woods,F,6,0.0,4,0,24,155.0,5.04
8,18,taytum clairmont,F,6,1.0,3,21,26,177.0,5.11
9,18,taytum clairmont,F,6,1.0,3,21,26,177.0,5.11
13,4,sarah steele,D,6,1.0,4,4,25,145.0,5.06
14,23,megan quinn,D,6,1.0,0,0,22,165.0,5.05
15,25,emma greco,D,6,0.0,0,0,22,150.0,5.08
16,15,natalie marcuzzi,F,6,0.0,0,0,27,135.0,5.08
17,91,jenna mcparland,F,6,0.0,0,0,33,140.0,5.08
18,91,henna mcparland,M,5,0.0,0,0,33,140.0,5.08
20,29,julie allen,F,6,0.0,0,0,26,145.0,5.07

**Bài tập**
- Top 3 cầu thủ có nhiều goals nhất
- Chiều cao trung bình của các cầu thủ
- Cầu thủ có cân nặng nhẹ nhất
- Cầu thủ lớn tuổi nhất và trẻ nhất
- Số lượng cầu thủ theo từng vị trí

In [ ]:
df = pd.read_csv('hockey_players_data.csv')

# Top 3 cầu thủ có nhiều bàn thắng nhất
top3_goals = df[['name', 'goals']].sort_values(by='goals', ascending=False)
print(top3_goals.head(3))

# Chiều cao trung bình
avg_height = df["height"].mean()
print("Chiều cao trung bình:", avg_height)

# Cầu thủ cân nặng nhẹ nhất
min_weight = df["weight"].min()
lightest_player = df[df["weight"] == min_weight]
print(lightest_player[["name", "weight"]])

# Lớn tuổi nhất
oldest = df[df["age"] == df["age"].max()]
print("Cầu thủ lớn tuổi nhất:")
print(oldest[["name", "age"]])

# Trẻ nhất
youngest = df[df["age"] == df["age"].min()]
print("\nCầu thủ trẻ nhất:")
print(youngest[["name", "age"]])

# Số lượng cầu thủ theo vị trí
position_count = df["position"].value_counts()
print(position_count)

                  name  goals
0  Mikyla Grant-Mentis    5.0
1     Lindsay Eastwood    4.0
2         Taylor Woods    4.0
Chiều cao trung bình: 5.072857142857142
                name  weight
16  Natalie Marcuzzi   135.0
Cầu thủ lớn tuổi nhất:
               name  age
17  Jenna McParland   33
18  Henna McParland   33

Cầu thủ trẻ nhất:
                   name  age
0   Mikyla Grant-Mentis   22
10    Shiann Darkangelo   22
14          Megan Quinn   22
15           Emma Greco   22
position
F    15
D     5
M     1
G     1
Name: count, dtype: int64