# **DATA FRAME: Đọc - ghi file**

## **1. Đọc - ghi file trực tiếp**

In [1]:
import pandas as pd
import numpy as np

In [3]:
# Khởi tạo dữ liệu dạng dictionary
data = {
    'name': ['Hải Nam', 'Đức Trung', 'Đức Minh', 'Mỹ Linh'],
    'age': [14, 2, 13, 15],
    'gender': ['male', 'male', 'prefer not to say', 'female']
}
# Khởi tạo DataFrame
df = pd.DataFrame(data)
# Hiển thị dữ liệu từ DataFrame
df

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

## **Tạo và đọc dữ liệu**

In [7]:
# Tạo dữ liệu CSV
df.to_csv('data.csv', index=False)

# Đọc dữ liệu CSV
df_csv = pd.read_csv('data.csv')
df_csv

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

In [8]:
# tải file về máy
from google.colab import files
files.download('data.csv')

In [9]:
# Tạo dữ liệu xlsx (file excel)
df = pd.DataFrame(data)
df.to_excel('data.xlsx', index=False)

# Đọc dữ liệu xlsx
df_xlsx = pd.read_excel('data.xlsx')
df_xlsx

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

In [10]:
# Tạo dữ liệu dạng json
df.to_json('data.json')

# Đọc dữ liệu dạng json
df_json = pd.read_json('data.json')
df_json

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

## **2. Đọc - ghi file từ máy tính**

In [11]:
# Tải file từ máy tính
from google.colab import files
files.upload()

Saving zoo.csv to zoo.csv

{'zoo.csv': b'row_number,animal,sound\n1,dog,woof\n2,cat,meow\n3,bird,tweet\n4,mouse,squeek\n5,cow,moo\n6,cow,moo\n7,frog,croak\n8,bird,tweet\n9,elephant,toot\n10,duck,quack\n11,fish,blub\n12,frog,croak\n13,seal,ow ow ow\n14,fox,'}

In [12]:
# Đọc file zoo.csv
  # index_col = 0: sử dụng cột đầu tiên trong dữ liệu để làm index
df = pd.read_csv('zoo.csv', index_col=0)
df

              animal     sound
row_number
1                dog      woof
2                cat      meow
3               bird     tweet
4              mouse    squeek
5                cow       moo
6                cow       moo
7               frog     croak
8               bird     tweet
9           elephant      toot
10              duck     quack
11              fish      blub
12              frog     croak
13              seal  ow ow ow
14               fox       NaN

In [13]:
# rename_axis(): đổi tên trục - axis (ngang hoặc dọc)
  # index (axis = 0): trục hàng
  # columns (axis = 1): trục cột

df = df.rename_axis(index=None) # xóa tên cột index
df

      animal     sound
1        dog      woof
2        cat      meow
3       bird     tweet
4      mouse    squeek
5        cow       moo
6        cow       moo
7       frog     croak
8       bird     tweet
9   elephant      toot
10      duck     quack
11      fish      blub
12      frog     croak
13      seal  ow ow ow
14       fox       NaN

# **TRUY CẬP DỮ LIỆU**

## **1. Truy cập theo cột**

In [14]:
# Truy cập cột 'animal' của df
animals = df['animal']
animals

1          dog
2          cat
3         bird
4        mouse
5          cow
6          cow
7         frog
8         bird
9     elephant
10        duck
11        fish
12        frog
13        seal
14         fox
Name: animal, dtype: object

In [15]:
# Hiển thị 3 phần tử đầu tiên
animals.head(3)

1     dog
2     cat
3    bird
Name: animal, dtype: object

In [16]:
# Hiển thị 3 phần tử cuối
animals.tail(3)

12    frog
13    seal
14     fox
Name: animal, dtype: object

Lưu ý:
- NaN là viết tắt của Not A Number
- Trong pandas, NaN dùng để biểu diễn dữ liệu bị thiếu (missing data)

In [18]:
# Truy cập nhiều cột
multi_col = df[['animal', 'sound']]
multi_col

      animal     sound
1        dog      woof
2        cat      meow
3       bird     tweet
4      mouse    squeek
5        cow       moo
6        cow       moo
7       frog     croak
8       bird     tweet
9   elephant      toot
10      duck     quack
11      fish      blub
12      frog     croak
13      seal  ow ow ow
14       fox       NaN

## **2. Truy cập theo hàng**

slice[start:end] => chạy từ start đến end-1

In [20]:
# Hiện từ hàng 5 đến 8
animals[4:9]

5         cow
6         cow
7        frog
8        bird
9    elephant
Name: animal, dtype: object

In [21]:
# Hiện từ đầu: [:end]
animals[:4]

1      dog
2      cat
3     bird
4    mouse
Name: animal, dtype: object

In [22]:
# Hiện đến hết: [start:]
animals[:9]

1         dog
2         cat
3        bird
4       mouse
5         cow
6         cow
7        frog
8        bird
9    elephant
Name: animal, dtype: object

## **3. Truy cập theo cả hàng và cột**

DataFrame.iloc[rows, columns]

In [23]:
# Hiển thị 3 dòng đầu tiên của cột thứ 2
df.iloc[:3, 1:2]

   sound
1   woof
2   meow
3  tweet

## **4. Truy cập có điều kiện**

In [24]:
# Tìm bản ghi mà data cột 'animal' == 'cat'
target = df[df['animal'] == 'cat']
target

  animal sound
2    cat  meow

# **Tổng hợp 1 số lệnh hay dùng với DataFrame**

In [25]:
# Khởi tạo dữ liệu dạng dictionary
data = {
    'name': ['Hải Nam', 'Đức Trung', 'Đức Minh', 'Mỹ Linh'],
    'age': [14, 2, 13, 15],
    'gender': ['male', 'male', 'prefer not to say', 'female']
}
# Khởi tạo DataFrame
df = pd.DataFrame(data)
# Hiển thị dữ liệu từ DataFrame
df

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

In [26]:
# Xem kiểu dữ liệu của từng cột
df.dtypes

name      object
age        int64
gender    object
dtype: object

In [27]:
# Xem số hàng và cột
df.shape

(4, 3)

In [28]:
# Tóm tắt thông tin của DataFrame: số dòng, số cột, số giá trị có dữ liệu, kiểu dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   gender  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [29]:
# Thống kê các cột dạng số
    # count: số dữ liệu (bản ghi)
    # mean: trung bình
    # std: độ lệch chuẩn
    # min, max: giá trị lớn/nhỏ nhất
df.describe()

             age
count   4.000000
mean   11.000000
std     6.055301
min     2.000000
25%    10.250000
50%    13.500000
75%    14.250000
max    15.000000

In [30]:
# Hiển thị các dòng đầu: df.head(n)
df.head(2)

        name  age gender
0    Hải Nam   14   male
1  Đức Trung    2   male

In [31]:
# Hiển thị các dòng cuối: df.tail(n)
df.tail(3)

        name  age             gender
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

In [32]:
# Đổi tên trục: rename_axis()
    # index (axis=0) → trục hàng
    # columns (axis=1) → trục cột
df = df.rename_axis(index=None) # Xóa tên cột index
df

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

In [33]:
# Đặt 1 cột làm index: set_index()
df = df.set_index('name')
df

           age             gender
name
Hải Nam     14               male
Đức Trung    2               male
Đức Minh    13  prefer not to say
Mỹ Linh     15             female

In [34]:
# Đưa index trở lại thành cột: reset_index()
df.reset_index()

        name  age             gender
0    Hải Nam   14               male
1  Đức Trung    2               male
2   Đức Minh   13  prefer not to say
3    Mỹ Linh   15             female

In [35]:
# Đổi tên cột hoặc index: df.rename(columns={"old_name":"new_name"})
df = df.rename(columns={"age":"tuổi"})
df

           tuổi             gender
name
Hải Nam      14               male
Đức Trung     2               male
Đức Minh     13  prefer not to say
Mỹ Linh      15             female